import type { Metadata } from "next";
import "./globals.css";
import AuthSessionProvider from "@/context/SessionProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <AuthSessionProvider>
        <body>
          {children}
          <Toaster />
        </body>
      </AuthSessionProvider>
    </html>
  );
}
